import React, { useEffect, useState } from 'react'
import Content from '../components/Content'
import FileTree from '../components/FileTree'
import Link from 'next/link'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCrop } from '@fortawesome/free-solid-svg-icons'
import Head from 'next/head';
import { useCookies } from 'react-cookie';
import { useMedia } from '../lib/hooks';


const ContentViewer = ({ host }) => {
  const [cookies, setCookie, removeCookie] = useCookies(["username"]);
  const { media, isLoading, isError } = useMedia(host, cookies.username)

  
  const [currentContent, setCurrentContent] = useState(["", "documents"])
  return (
    <main className='viewer'>
      <Head>
        <title>A Personal Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? <h1>Loading...</h1> : isError?<h1>Error while getting media...</h1>:<>
        <FileTree
          BackComponent={<Link href="/selector"><div className='link' ><FontAwesomeIcon icon={faCrop} /></div></Link>}
          setCurrentContent={setCurrentContent} media={media}></FileTree>
        <Content currentContent={currentContent} host={host}></Content>
      </>}
    </main>
  )
}

export default ContentViewer

export async function getStaticProps() {

  return {
    props: {
      host: process.env.VIDEO_SERVER_HOST,
    }
  }
}
